@startuml

package "Entities" {
    class Band {
        - bandId: UUID
        - bandName: String
        - description: String
        - formationYear: LocalDate
        - albums: List<Album>
    }

    class Album {
        - albumId: UUID
        - albumName: String
        - releaseYear: LocalDate
        - band: Band
    }
}

Band "1" -- "0..*" Album

@enduml
